import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import './globals.css';
import { Toaster } from 'sonner';
import { ProviderQueryClient } from '@/providers/QueryClient';

import { CompanyProvider } from '@/hooks/use-company-context';
import { AuthProvider } from '@/providers/auth-provider';

const manrope = Manrope({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'NexManage',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={`${manrope.className} antialiased`}>
        <Toaster position="top-right" closeButton richColors />
        <CompanyProvider>
          <ProviderQueryClient>
            <AuthProvider>{children}</AuthProvider>
          </ProviderQueryClient>
        </CompanyProvider>
      </body>
    </html>
  );
}
